# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.04+wlrmultivid1'

RELEASE_GIT_HEAD = 'df21db7e62f74ed4cb5810905736ad0e0b8ab8b5'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
